name: Deploy OpenTofu

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.7.2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Init OpenTofu
      run: tofu init

    - name: Plan
      run: tofu plan -out=tfplan

    - name: Apply
      run: tofu apply -auto-approve tfplan
